services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  monomart-config:
    image: monomart-config:v6.0
    container_name: 'monomart-config'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://monomart-config:8083/application/default"]
      interval: 5s
      timeout: 10s
      retries: 20
    ports:
      - 8083:8083

  postgres:
    image: 'postgres:latest'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=commercedatabase,inventorydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=appuser
    ports:
      - '5432:5432'

  monomart:
    image: monomart:v6.0
    container_name: 'monomart'
    environment:
      - ZIPKIN_HOST=tempo:9411
      - LOKI_HOST=loki:3100
    ports:
      - 8080:8080

  monomart-agw:
    image: monomart-agw:v6.0
    container_name: 'monomart-agw'
    environment:
      - INVENTORY_HOST=host.docker.internal:8081
      - COMMERCE_HOST=host.docker.internal:8082
      - MONOMART_HOST=host.docker.internal:8080
      - CONFIG_SERVER_HOST=host.docker.internal:8083
      - ZIPKIN_HOST=tempo:9411
      - LOKI_HOST=loki:3100
    depends_on:
      monomart-config:
        condition: service_healthy
    ports:
      - 8888:8888

  monomart-commerce:
    image: monomart-commerce:v6.0
    container_name: 'monomart-commerce'
    environment:
#      - SPRING_PROFILES_ACTIVE=chaos
      - PRODUCT_API_URL=http://monomart-agw:8888
      - RABBIT_HOST=rabbitmq
      - ZIPKIN_HOST=tempo:9411
      - LOKI_HOST=loki:3100
      - POSTGRES_HOST=postgres
    ports:
      - 8082:8082

  monomart-inventory:
    image: monomart-inventory:v6.0
    container_name: 'monomart-inventory'
    environment:
#      - SPRING_PROFILES_ACTIVE=chaos
      - RABBIT_HOST=rabbitmq
      - ZIPKIN_HOST=tempo:9411
      - LOKI_HOST=loki:3100
      - POSTGRES_HOST=postgres
    ports:
      - 8081:8081

  prometheus:
    image: bitnami/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus_config.yml:/opt/bitnami/prometheus/conf/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "9091:3000"
    volumes:
      - /tmp/grafana/storage:/var/lib/grafana
      - ./observability/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
      - ./observability/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./observability/grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo-local.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml