version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  monomart-config:
    image: monomart-config-final:latest
    container_name: 'monomart-config'
    environment:
      CI_JOB_TOKEN: ${CI_JOB_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://monomart-config:8083/application/default"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 8083:8083

  monomart:
    image: monomart-final:latest
    container_name: 'monomart'
    ports:
      - 8080:8080

  monomart-agw:
    image: monomart-agw-final:latest
    container_name: 'monomart-agw'
    environment:
      - INVENTORY_HOST=host.docker.internal:8081
      - COMMERCE_HOST=host.docker.internal:8082
      - MONOMART_HOST=host.docker.internal:8080
      - CONFIG_SERVER_HOST=host.docker.internal:8083
      - SPRING_PROFILES_ACTIVE=mono
    depends_on:
      monomart-config:
        condition: service_healthy
    ports:
      - 8888:8888

  log-stream-sink:
    image: springcloudstream/log-sink-rabbit:latest
    container_name: product-purchased-log-sink
    environment:
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION=commerce
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_GROUP=logger.product.purchased
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONTENT_TYPE=application/json
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONTENT_BINDER=rabbit
      - SPRING_CLOUD_STREAM_RABBIT_BINDINGS_INPUT_CONSUMER_BINDING_ROUTING_KEY=product.purchased
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_TYPE=rabbit
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_USERNAME=guest
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
#  monomart-commerce:
#    image: monomart-commerce-final:latest
#    container_name: 'monomart-commerce'
#    environment:
#      - PRODUCT_API_URL=http://monomart-inventory:8081
#      - RABBIT_HOST=rabbitmq
#    ports:
#      - 8082:8082
#
#  monomart-inventory:
#    image: monomart-inventory-final:latest
#    container_name: 'monomart-inventory'
#    environment:
#      - RABBIT_HOST=rabbitmq
#    ports:
#      - 8081:8081